{{- if and .Values.mysql.enabled .Values.mysql.persistence.enabled (not .Values.mysql.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cattr.mysql.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cattr.mysql.labels" . | nindent 4 }}
  {{- with (include "cattr.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.mysql.persistence.accessModes | nindent 4 }}
  {{- include "cattr.storageClass" (dict "persistence" .Values.mysql.persistence "global" .Values.global) | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
{{- end }}
