{{- if and .Values.persistence.screenshots.enabled (not .Values.persistence.screenshots.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cattr.fullname" . }}-screenshots
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cattr.labels" . | nindent 4 }}
  {{- with (include "cattr.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.screenshots.accessModes | nindent 4 }}
  {{- include "cattr.storageClass" (dict "persistence" .Values.persistence.screenshots "global" .Values.global) | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.persistence.screenshots.size }}
{{- end }}
