apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cattr.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cattr.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- include "cattr.annotations" . | nindent 4 }}
type: Opaque
data:
  APP_KEY: {{ if .Values.cattr.appKey }}{{ printf "base64:%s" .Values.cattr.appKey | b64enc }}{{ else }}{{ printf "base64:%s" (randAlphaNum 32 | b64enc) | b64enc }}{{ end }}
  DB_USERNAME: {{ .Values.database.username | b64enc }}
  DB_PASSWORD: {{ .Values.database.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | b64enc }}
